oracle_databases:                                               # Dictionary describing the databases to be installed
      - home: 21000-211005                                            # 'Last' directory in ORACLE_HOME path (e.g /u01/app/oracle/12.2.0.1/db1)
        oracle_db_name: cdb12                                # Database name
        oracle_db_type: SI                                   # Type of database (RAC,RACONENODE,SI)
        is_container: True                                # (true/false) Is the database a container database
        storage_type: FS                                     # Database storage to be used. ASM or FS.
        oracle_db_mem_totalmb: 1024                            # Amount of RAM to be used for SGA
        oracle_database_type: MULTIPURPOSE                   # MULTIPURPOSE|DATA_WAREHOUSING|OLTP
        redolog_size: 75M
        redolog_groups: 3
        datafile_dest: /u01/oradata
        recoveryfile_dest: /u01/fra
        listener_name: LISTENER                              # This home will have a listener configured
        listener_port: 1521
        archivelog: True
        flashback: True
        force_logging: True
        state: present
        create: True
        # tablespaces:
        #      - { name: users, size: 10M, bigfile: True, autoextend: false , next: 5M, maxsize: 500M, content: permanent, state: present }
        init_parameters:
             - {name: db_create_file_dest, value: '/u01/oradata', scope: both, state: present}
             - {name: db_create_online_log_dest_1, value: '/u01/fra', scope: both, state: present}
             - {name: db_recovery_file_dest, value: '/u01/fra', scope: both, state: present}
             - {name: db_recovery_file_dest_size, value: 20G, scope: both, state: present}
        # services:
        #      - { name: service2,  state: started }
        # users:
        #   - schema: c##dba
        #     container: all
        #     grants:
        #          - dba
        #     state: present
