db_homes_config:
  21000-211005:
    home: 21000-211005
    version: 21.0.0.0
    edition: EE

db_homes_installed:
     - home: 21000-211005
       apply_patches: False
       state: present


default_dbpass: Oracle123
oracle_base: /u01/app/oracle
oracle_home_db: "{%- if dbh is defined -%}
                    {%- if db_homes_config[dbh.home]['oracle_home'] is defined  -%}
                         {{db_homes_config[dbh.home]['oracle_home']}}
                    {%- else -%}
                         {{oracle_base}}/{{db_homes_config[dbh.home]['version']}}/{{db_homes_config[dbh.home]['home']}}
                    {%- endif -%}
                 {%- elif item.0 is defined -%}
                    {%- if db_homes_config[item.0.home]['oracle_home'] is defined  -%}
                         {{db_homes_config[item[0].home]['oracle_home']}}
                    {%- else -%}
                         {{oracle_base}}/{{db_homes_config[item.0.home]['version']}}/{{db_homes_config[item.0.home]['home']}}
                    {%- endif -%}
                 {%- elif item[1] is defined -%}
                    {%- if db_homes_config[item[1].home]['oracle_home'] is defined  -%}
                         {{db_homes_config[item[1].home]['oracle_home']}}
                    {%- else -%}
                         {{oracle_base}}/{{db_homes_config[item[1].home]['version']}}/{{db_homes_config[item[1].home]['home']}}
                    {%- endif -%}
                 {%- elif item is defined -%}
                    {%- if db_homes_config[item.home]['oracle_home'] is defined  -%}
                         {{db_homes_config[item.home]['oracle_home']}}
                    {%- else -%}
                         {{oracle_base}}/{{db_homes_config[item.home]['version']}}/{{db_homes_config[item.home]['home']}}
                    {%- endif -%}
                 {%- endif -%}"

db_version: "{%- if dbh is defined and db_homes_config[dbh.home] is defined -%}
                 {%- if db_homes_config[dbh.home]['version'] is defined  -%}
                      {{db_homes_config[dbh.home]['version']}}
                 {%- endif -%}
             {%- elif item.0 is defined and db_homes_config[item.0.home] is defined -%}
                 {%- if db_homes_config[item.0.home]['version'] is defined  -%}
                      {{db_homes_config[item.0.home]['version']}}
                  {%- endif -%}
             {%- elif item[0] is defined and db_homes_config[item[0].home] is defined -%}
                 {%- if db_homes_config[item[0].home]['version'] is defined  -%}
                      {{db_homes_config[item[0].home]['version']}}
                 {%- endif -%}
             {%- elif item[1] is defined and db_homes_config[item[1].home] is defined -%}
                 {%- if db_homes_config[item[1].home]['version'] is defined  -%}
                      {{db_homes_config[item[1].home]['version']}}
                 {%- endif -%}
             {%- elif item is defined and db_homes_config[item.home] is defined -%}
                 {%- if db_homes_config[item.home]['version'] is defined  -%}
                      {{db_homes_config[item.home]['version']}}
                 {%- endif -%}
             {%- endif -%}"

oracle_home_gi: "{% if configure_cluster %}{{ oracle_home_gi_cl }}{% else %}{{ oracle_home_gi_so }}{% endif %}"
oracle_home_gi_cl: "/u01/app/{{ oracle_install_version_gi }}/grid" # ORACLE_HOME for Grid Infrastructure (Clustered)
oracle_home_gi_so: "{{ oracle_base }}/{{ oracle_install_version_gi }}/grid" # ORACLE_HOME for Grid Infrastructure (Stand Alone)
